/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wizwa9381
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /**
     * 
     * @param estimates
     * @param bookNames
     * @param wordCount 
     */
    public void textSetting(int estimates [], String bookNames [], int wordCount []){
        bookOneNameLabel.setText(bookNames[0]);
        bookTwoNameLabel.setText(bookNames[1]);
        bookThreeNameLabel.setText(bookNames[2]);
        wordCountBookOneLabel.setText(wordCount[0] + "");
        wordCountBookTwoLabel.setText(wordCount[1] + "");
        wordCountBookThreeLabel.setText(wordCount[2] + "");
        int offByBookOne = Math.abs(estimates[0]-wordCount[0]);
        int offByBookTwo = Math.abs(estimates[1]-wordCount[1]);
        int offByBookThree = Math.abs(estimates[2]-wordCount[2]);
        offByBookOneLabel.setText(offByBookOne + "");
        offByBookTwoLabel.setText(offByBookTwo + "");
        offByBookThreeLabel.setText(offByBookThree + "");
    }
    
    /**
     * Method to get the user inputs
     * @return estimates from the user
     */
    public int [] parsing(){
        int [] estimates = new int [3];
        try{
            estimates[0] = Integer.parseInt(estimateBookOneTextField.getText());
        }
        catch (NumberFormatException e){
            System.err.println("That is not a valid input for book 1 estimate.");
        }
        try {
            estimates[1] = Integer.parseInt(estimateBookTwoTextField.getText());
        }
        catch (NumberFormatException e){
            System.err.println("That is not a valid input for book 2 estimate.");
        }
        try {
            estimates[2] = Integer.parseInt(estimateBookThreeTextField.getText());
        }
        catch (NumberFormatException e){
            System.err.println("That is not a valid input for book 3 estimate.");
        }
        return estimates;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        estimateBookOneTextField = new javax.swing.JTextField();
        estimateBookTwoTextField = new javax.swing.JTextField();
        estimateBookThreeTextField = new javax.swing.JTextField();
        wordCountBookOneLabel = new javax.swing.JLabel();
        wordCountBookTwoLabel = new javax.swing.JLabel();
        wordCountBookThreeLabel = new javax.swing.JLabel();
        offByBookOneLabel = new javax.swing.JLabel();
        offByBookTwoLabel = new javax.swing.JLabel();
        offByBookThreeLabel = new javax.swing.JLabel();
        instructionsOneLabel = new javax.swing.JLabel();
        instructionsTwoLabel = new javax.swing.JLabel();
        instructionThreeLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        bookNameLabel = new javax.swing.JLabel();
        bookOneNameLabel = new javax.swing.JLabel();
        bookTwoNameLabel = new javax.swing.JLabel();
        bookThreeNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        titleLabel.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        titleLabel.setText("Amount of words per book in the Lord of the Rings trilogy");

        estimateBookOneTextField.setText("0");

        estimateBookTwoTextField.setText("0");

        estimateBookThreeTextField.setText("0");

        instructionsOneLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        instructionsOneLabel.setText("Enter an estimate for how many words per novel");

        instructionsTwoLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        instructionsTwoLabel.setText("Actual number of words");

        instructionThreeLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        instructionThreeLabel.setText("Off by");

        startButton.setText("Show");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        bookNameLabel.setText("Book names");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bookThreeNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(bookTwoNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bookOneNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(estimateBookOneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(estimateBookTwoTextField)
                                .addComponent(estimateBookThreeTextField))
                            .addGap(134, 134, 134)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(wordCountBookOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wordCountBookTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wordCountBookThreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addGap(16, 16, 16))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bookNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instructionsOneLabel)
                            .addGap(18, 18, 18)
                            .addComponent(instructionsTwoLabel)))
                    .addGap(53, 53, 53)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(instructionThreeLabel)
                        .addComponent(offByBookOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(offByBookTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(offByBookThreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                    .addGap(18, 18, 18))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startButton)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructionsOneLabel)
                    .addComponent(instructionsTwoLabel)
                    .addComponent(instructionThreeLabel)
                    .addComponent(bookNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordCountBookOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(offByBookOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(estimateBookOneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bookOneNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordCountBookTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(offByBookTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estimateBookTwoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookTwoNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimateBookThreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordCountBookThreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(offByBookThreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookThreeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(startButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        //Arrays
        String bookNames [] = {"Fellowship of the Ring","The Two Towers","The Return of the King"};
        int wordCount [] = {177227, 143436, 134462};
        int estimates [];
        //Methods
        estimates = parsing();
        textSetting(estimates,bookNames,wordCount);
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookNameLabel;
    private javax.swing.JLabel bookOneNameLabel;
    private javax.swing.JLabel bookThreeNameLabel;
    private javax.swing.JLabel bookTwoNameLabel;
    private javax.swing.JTextField estimateBookOneTextField;
    private javax.swing.JTextField estimateBookThreeTextField;
    private javax.swing.JTextField estimateBookTwoTextField;
    private javax.swing.JLabel instructionThreeLabel;
    private javax.swing.JLabel instructionsOneLabel;
    private javax.swing.JLabel instructionsTwoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel offByBookOneLabel;
    private javax.swing.JLabel offByBookThreeLabel;
    private javax.swing.JLabel offByBookTwoLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel wordCountBookOneLabel;
    private javax.swing.JLabel wordCountBookThreeLabel;
    private javax.swing.JLabel wordCountBookTwoLabel;
    // End of variables declaration//GEN-END:variables
}
